version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env

  api: 
    build: ./api
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes: 
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  client:
    build: ./client
    command: quasar dev
    volumes:
        - ./client:/client
    ports:
        - 8080:8080
    depends_on:
        - api