version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 5s
      retries: 25
  api:
    build: ./api
    command: ["sh", "entrypoint.sh"]
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy

  client:
    container_name: "client"
    build:
      context: ./client/
      target: "develop-stage"
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./client:/client"
    command: /bin/sh -c "yarn && quasar dev"
    depends_on:
      - api
