version: '3.3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db:/var/lib/postgresql/
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
  api:
    build: ./api
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    container_name: api
    volumes:
      - ./api:/api
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: ./client
    #command: yarn dev
    volumes:
      - ./client:/code
    ports:
      - "8080:8080"
    depends_on:
      - api