version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  api:
    build: api/
    command: /bin/sh -c "cd api && ./run_tests.sh"
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    depends_on:
      - db