version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: circleci/python:3.6.4
      - image: circleci/postgres:9.6.2
    steps:
      - checkout
      - run:
          command: |
            pip3 install virtualenv
            virtualenv env
            . env/bin/activate
            pip install djangorestframework psycopg2 django-cors-headers
      - run:
          name: Running tests
          command: |
            . env/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/