version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          DATABASE_URL: postgresql://myuser@localhost:5432/circle_test
      - image: circleci/postgres:12
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
    steps:  
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install python-pip python-dev libpq-dev postgresql postgresql-contrib 
      - run:
          command: |
            pip3 install virtualenv
            virtualenv env
            . env/bin/activate
            pip install djangorestframework psycopg2 django-cors-headers
      - run:
          name: Setup the database
          command: psql -h localhost -p 5432 -U myuser -d circle_test -a -f schema.sql
      - run:
          name: Running tests
          command: |
            . env/bin/activate
            cd api/
            python3 manage.py test
      - store_artifacts:
          path: test-reports/