version: 2
jobs:
  build:
    working_directory: ~/api
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWOR
        environment:
          POSTGRES_HOST: postgresql://root@localhost/circle_test
      - image: circleci/postgres:12
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_DB: myproject
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: password
    steps:  
      - checkout
      - run:
          command: |
            pip3 install virtualenv
            virtualenv env
            . env/bin/activate
            pip install djangorestframework psycopg2 django-cors-headers
      - run:
          name: Running tests
          command: |
            . env/bin/activate
            cd api/
            python3 manage.py test
      - store_artifacts:
          path: test-reports/