# Generated by Django 3.2 on 2021-04-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240, verbose_name='Title')),
                ('description', models.CharField(max_length=240, verbose_name='Title')),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
