# This is a basic workflow to help you get started with Actions

name: API-CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - "api/**"
  pull_request:
    branches: [ master ]
    paths:
      - "api/**"

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run build api
        run: docker-compose up -d api
      - name: docker ps
        run: docker-compose ps
        env:
          DB_HOST: db
          DB_NAME: myproject
          DB_USER: myuser
          DB_PASSWORD: password
  
  quality_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sonar Scan
        uses: SonarSource/sonarcloud-github-action@v1.4
        with:
          projectBaseDir: api
        env:
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN_API }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [build, quality_code]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "api/"
    steps:
      - uses: actions/checkout@v2
      - name: DockerHub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
      - name: Docker image
        run: docker build . --file Django.Dockerfile --tag guilhermemp/gces-trabalho-individual-2020-2:api_latest

      - name: Docker Push
        run: docker push guilhermemp/gces-trabalho-individual-2020-2:api_latest
