name: Deploy to heroku [CLIENT].

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push and Release a Docker container to Heroku [CLIENT].
        uses: gonuit/heroku-docker-deploy@v1.3.2 
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_CLIENT }}
          dockerfile_directory: ./client
          dockerfile_name: dockerfile.prod
          docker_options: "--no-cache"
          process_type: web