name: Backend CI/CD

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - master
      - develop

# three job definition
jobs:
  health-check-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Cache dependency
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Check Code Analisys
        run: docker-compose run api pycodestyle --statistics .
      - name: Make Migrations
        run: docker-compose run api python3 manage.py migrate
      - name: Run Tests
        run: docker-compose run api python3 manage.py test
