
name: CI-LINTER

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
      - master

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - uses: lgeiger/pyflakes-action@master

  client:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: cd client && npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint: true