name: COV-CI
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  workflow_run:
    # Allows you to run this workflow manually from the Actions tab
    workflows: ["API-CI", "CLIENT-CI"]
    types: [completed]
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # The type of runner that the job will run on
  on-success:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: paambaati/codeclimate-action@v2.7.5
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.TEST_COVERAGE_TOKEN }}
      with:
        coverageLocations: |
          ${{github.workspace}}/client/test/jest/coverage/*
          ${{github.workspace}}/api/*
        debug: true
