name: CI-COVERAGE
on:
  push:
    branches: 
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create env file
      run: |
        touch .env
        echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env
        echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env

    - name: build
      run: docker-compose up --build -d
    
    - name: test api
      run: docker-compose run api coverage run manage.py test
    
    - name: generate api xml
      run: docker-compose run api coverage xml
    
    - name: test client
      run: docker-compose run client quasar test --unit jest
    
    - uses: codecov/codecov-action@v1
      with:
        files: ${{github.workspace}}/api/coverage.xml, ${{github.workspace}}/client/test/jest/coverage/lcov.info
        fail_ci_if_error: true
        verbose: true